config/routes.rb
Rails.application.routes.draw do
  devise_for :users,controllers: { 
    registrations: 'users/registrations'
  }
  root 'users#index'
  get "search" => "searches#search"
  get 'rooms/own', to: 'rooms#own'
  get 'reservations/confirm'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # ↓テスト中

  resources :users do
    collection do
      get 'account'
      get 'profile'
      get 'account/edit', action: 'edit'
      get 'profile/edit', action: 'edit'
    end
  end

  resources :rooms
  resources :reservations

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :name, presence: true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :password, presence: true, on: :create

  mount_uploader :img, ImgUploader

  def update_without_current_password(params, *options)
    params.delete(:current_password)

    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update_attributes(params, *options)
    clean_up_passwords
    result
  end

  has_many :rooms
  has_many :reservations
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  def edit
    super
  end

  # PUT /resource
  def update
    super
  end

  #任意  更新後のパスを指定
  def after_update_path_for(resource)
    if request.referer.include?("account")
      account_users_path(current_user)
    else
      profile_users_path(current_user)
    end
  end

  #必須  更新（編集の反映）時にパスワード入力を省く
  def update_resource(resource, params)
    resource.update_without_password(params)
  end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def account
    @user = current_user
  end

  def profile
    @user = current_user
    @user_image = "default_img/default-avatar.png"
    if @user.img.present?
        @user_image = @user.img
    end
  end

  def edit
    @user = current_user
    @path = request.referer
    if @path.include?("account")
        @data = 'account';
    elsif @path.include?("profile")
        @data = 'profile';
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email ,:img)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/account.html.erb
<div class="user-info">
<h2>設定</h2>
    <div class="user-setting">
        <table class="link-user-setting">
            <tr>
                <td><%= link_to "アカウント", account_users_path(@user) %></td>
            </tr>
            <tr>
                <td><%= link_to "プロフィール", profile_users_path(@user) %></td>
            </tr>
        </table>
        <table class="user-data">
            <thead>
                <tr>
                    <th>アカウント</th>
                    <th>
                        <%= link_to "編集", account_edit_users_path(@user) %>
                    </th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <th>メールアドレス</th>
                    <td>
                        <%= @user.email %>
                    </td>
                <tr>
                <tr>
                    <th>パスワード</th>
                    <td>*********</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

app/views/users/edit.html.erb
<div class="user_info_edit">
  <h2>ユーザ情報の編集</h2>

  <script>
    window.addEventListener('DOMContentLoaded', function(){
      var data = "<%= @data %>";
      console.log(data);
      if(data == "account"){
        console.log("ifを実行したよ");
        $('.account').css('display', 'block');
        $('.profile').css('display', 'none');
      }else if(data == "profile"){
        $('.account').css('display', 'none');
        $('.profile').css('display', 'block');
      }
    });
  </script>

  <%= form_for(@user, as: :user, url: registration_path(@user), html: { method: :put }) do |f| %>
    <%= render "devise/shared/error_messages", resource: @user %>
      <div class="user-setting">
          <table class="link-user-setting">
              <tr>
                  <td><%= link_to "アカウント", account_users_path(@user) %></td>
              </tr>
              <tr>
                  <td><%= link_to "プロフィール", profile_users_path(@user) %></td>
              </tr>
          </table>
          <table class="user-data-edit">
              <thead>
                  <tr>
                      <th class="account">アカウント</th>
                      <th class="profile">プロフィール</th>
                  </tr>
              </thead>
              <tbody>
                  <tr class="field profile">
                      <th><%= f.label :img %></th>
                      <td>
                        <%= f.file_field :img %>
                      </td>
                  <tr>
                  <tr class="field profile">
                      <th><%= f.label :name %></th>
                      <td>
                        <%= f.text_field :name, autocomplete: "name" %>
                      </td>
                  <tr>
                  <tr class="field profile">
                      <th><%= f.label :introduction %></th>
                      <td>
                        <%= f.text_area :introduction %>
                      </td>
                  <tr>
                  <tr class="field account">
                      <th><%= f.label :email %></th>
                      <td>
                        <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
                      </td>
                  <tr>
                  <tr class="field account">
                      <th><%= f.label :email %></th>
                      <td>
                        <%= f.label :password %> <i>(変更しない場合は空白のままにしてください)</i><br />
                        <%= f.password_field :password, autocomplete: "new-password" %>
                        <% if @minimum_password_length %>
                          <br />
                          <em><%= @minimum_password_length %> characters minimum</em>
                        <% end %>
                      </td>
                  </tr>
                  <tr class="field account">
                    <th><%= f.label :password_confirmation %></th>
                    <td>
                      <%= f.password_field :password_confirmation, autocomplete: "new-password" %>
                    </td>
                  </tr>
              </tbody>
              <tfoot>
                <tr>
                  <td class="actions"><%= f.submit "保存" %></td>
                  <td><%= link_to "キャンセル", :back %></td>
                </tr>
              </tfoot>
          </table>
      </div>
  <% end %>
</div>

app/views/users/index.html.erb
<section class="FirstView">
    <div class="container">
        <h2>Potepan Shareで<br>
        まだ体験したことのない<br>
        旅をしよう
        </h2>
        <%= form_with url: rooms_path, local: true, method: :get do |f| %>
            <%= f.text_field :word, :placeholder => "エリア名を入力" %>
            <%= f.hidden_field :search, value: "partial_match" %>
            <%= f.submit "検索", class: "btn-sm btn-primary" %>
        <% end %>
    </div>
</section>
<section>
    <div class="container">
        <h3>おすすめのエリア</h3>
        <div class="recommend-imgs">
            <%= link_to image_tag("recommend-area/tokyo.jpg", size: "300x400", alt: "東京イメージ画像"),
            rooms_path(word: "東京", search: "forward_match") %>
            <%= link_to image_tag("recommend-area/osaka.jpg",  size: "300x400", alt: "大阪イメージ画像"),
            rooms_path(word: "大阪") %>
            <%= link_to image_tag("recommend-area/kyoto.jpg",  size: "300x400", alt: "京都イメージ画像"),
            rooms_path(word: "京都") %>
            <%= link_to image_tag("recommend-area/sapporo.jpg",  size: "300x400", alt: "札幌イメージ画像"),
            rooms_path(word: "札幌") %>
        </div>
    </div>
</section>

app/views/users/new.html.erb
<h1>こんにちは、<%= current_user.username %>さん</h1>
<p>ユーザー用ページです。</p>

app/views/users/profile.html.erb
<div class="user-info">
<h2>設定</h2>
    <div class="user-setting">
        <table class="link-user-setting">
            <tr>
                <td><%= link_to "アカウント", account_users_path(@user) %></td>
            </tr>
            <tr>
                <td><%= link_to "プロフィール", profile_users_path(@user) %></td>
            </tr>
        </table>
        <table class="user-data">
            <thead>
                <tr>
                    <th>プロフィール</th>
                    <th>
                        <%= link_to "編集", profile_edit_users_path(@user) %>
                    </th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <th>画像</th>
                    <td class="img-profile">
                        <%= image_tag  "#{@user_image}" %>
                    </td>
                <tr>
                <tr>
                    <th>名前</th>
                    <td>
                        <%= @user.name %>
                    </td>
                <tr>
                <tr>
                    <th>自己紹介</th>
                    <td><%= @user.introduction %></td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

app/views/users/show.html.erb
<h2>Users</h2>
<hr />

<p>
    <strong>画像</strong>
    <%= image_tag  "#{@user_image}" %>
</p>
<p>
    <strong>ユーザー名</strong>
    <%= @user.name %>
</p>
<p>
    <strong>e-mail</strong>
    <%= @user.email %>
</p>
<p>
    <strong>パスワード</strong>
    <p>*********</p>
</p>
<p>
    <strong>自己紹介</strong>
    <%= @user.introduction %>
</p>
<p>
    <%= link_to "編集", edit_user_registration_path(current_user) %>
</p>