config/routes.rb
Rails.application.routes.draw do
  devise_for :users,controllers: { 
    registrations: 'users/registrations'
  }
  root 'users#index'
  get "search" => "searches#search"
  get 'rooms/own', to: 'rooms#own'
  get 'reservations/confirm'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # ↓テスト中

  resources :users do
    collection do
      get 'account'
      get 'profile'
      get 'account/edit', action: 'edit'
      get 'profile/edit', action: 'edit'
    end
  end

  resources :rooms
  resources :reservations

end

app/views/shared/_error.html.erb
<% if obj.errors.any? %>
<% obj.errors.full_messages.each do |message| %>
  <ul>
    <li><%= message %></li>
  </ul>
<% end %>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
    <div>
        <%= link_to image_tag("logo.png", class:"image_switch", alt: "アイコン"), users_path %>
        <p>Copyright © Potepan Share 2023 All rights reserved</p>
    </div>
</footer>

app/views/shared/_header.html.erb
<header class="header">
  <div class="container">
    <h1>
        <%= link_to image_tag("logo.png", class:"image_switch", alt: "アイコン"), users_path %>
    </h1>
    <nav>
    <% if user_signed_in? %>
      <div class="linkArea-user">
          <% if current_user.img.blank? %>
            <%= image_tag "default_img/default-avatar.png"  %>
          <% else %>
            <%= image_tag "#{current_user.img}"  %>
          <% end %>
            <span>
              <%= current_user.name %>
            </span>
      </div>
      <ul class="dropdown-menu">
        <li><%= link_to '施設の新規登録', new_room_path %></li>
        <li><%= link_to '予約済み一覧', reservations_path %></li>
        <li><%= link_to '登録済み一覧', rooms_own_path %></li>
        <li><%= link_to 'アカウント設定', account_users_path(current_user) %></li>
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
      </ul>
      <% else %>
      <%= link_to '新規登録', new_user_registration_path %>
      <%= link_to 'ログイン', new_user_session_path %>
    <% end %>
    </nav>
  </div>
</header>

app/views/shared/_search.html.erb
<div class="search_area">
    <%= form_with url: rooms_path, local: true, method: :get do |f| %>
        <%= f.text_field :word, :placeholder => "エリア名を入力" %>
        <%= f.text_field :word2, :placeholder => "キーワード名を入力" %>
        <%= f.hidden_field :search, value: "Multiple_search" %>
        <%= f.submit "検索", class: "btn-sm btn-primary" %>
    <% end %>
</div>