config/routes.rb
Rails.application.routes.draw do
  devise_for :users,controllers: { 
    registrations: 'users/registrations'
  }
  root 'users#index'
  get "search" => "searches#search"
  get 'rooms/own', to: 'rooms#own'
  get 'reservations/confirm'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # ↓テスト中

  resources :users do
    collection do
      get 'account'
      get 'profile'
      get 'account/edit', action: 'edit'
      get 'profile/edit', action: 'edit'
    end
  end

  resources :rooms
  resources :reservations

end

app/models/room.rb
class Room < ApplicationRecord
    validates :name, presence: true
    validates :introduction, presence: true
    validates :price, numericality: {greater_than_or_equal_to: 1}, presence: true
    validates :address, presence: true

  def self.looks(search,word,word2)
    if search == "partial_match" #キーワード検索
        Room.where("address LIKE?","%#{word}%")
    elsif search == "Multiple_search"
        Room.where("address LIKE? AND name LIKE?","%#{word}%","%#{word2}%").or(Room.where("address LIKE? AND introduction LIKE?","%#{word}%","%#{word2}%"))
    else #エリア検索
        Room.where("address LIKE?","#{word}%")
    end
  end

    belongs_to :user
    has_many :reservations

    mount_uploader :img, ImgUploader
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @users = User.all
    @rooms = Room.all

    @word = params[:word]
    @word2 = params[:word2]
    @search = params[:search]
    @search_rooms = Room.looks(params[:search],params[:word],params[:word2])
  end

  def new
    @user = current_user
    @room = Room.new
  end

  def create
    @room = Room.new(params.require(:room).permit(:name, :introduction, :price, :address, :img, :user_id))

    @room_image = "default_img/default-room.png"
    if @room.img.present?
        @room_image = @room.img
    end

     if @room.save
       flash[:notice] = "新規施設登録をしました"
       redirect_to :rooms
     else
       @user = User.find_by(params[:room][:user_id])
       render "new"
     end
  end

  def show
    @room = Room.find(params[:id])

    # 以下は予約機能で使用する
    @user = current_user
    @reservation = Reservation.new
  end

  def edit
  end

  def update
  end

  def destroy
  end

  def own
    @user = current_user
    @rooms = @user.rooms
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/index.html.erb
<%= render "shared/search" %>
<div class="room_list">
    <h3><%= @search_rooms.count %>件が見つかりました</h2>

    <table>
    <thead>
        <tr>
        <th>施設画像</th>
        <th>施設名</th>
        <th>施設詳細</th>
        <th>価格</th>
        <th>住所</th>
        <th></th>
        </tr>
    </thead>
    
    <tbody>
        <% @search_rooms.each do |room| %>
        <tr>
            <td class="img-profile">
                <% if room.img.blank?  %>
                    <%= image_tag  "default_img/default-room.png" %>
                <% else %>
                    <%= image_tag  "#{room.img}" %>
                <% end %>
            </td>
            <td><%= link_to room.name, room_path(room.id) %></td>
            <td><%= room.introduction %></td>
            <td>￥<%= room.price %>〜</td>
            <td><%= room.address %></td>
            <td class="link_btn"><%= link_to "詳細はこちら", room_path(room.id) %></td>
        </tr>
        <% end %>
    </tbody>
    </table>
</div>

app/views/rooms/new.html.erb
<div class="room_new">
  <h3>新規施設登録</h3>
  <%= render "shared/error", obj: @room %>
  
  <%= form_with model: @room do |f| %>
    <table>
      <tr>
        <th><%= f.label :name, "施設名" %></th>
        <td><%= f.text_field :name, class:"room-name" %></td>
      </tr>
      <tr>
          <th><%= f.label :introduction, "施設詳細" %></th>
          <td><%= f.text_area :introduction, class:"room-name" %></td>
      </tr>
      <tr>
          <th><%= f.label :price, "料金" %></th>
          <td><%= f.text_field :price, class:"room-name" %></td>
      </tr>
      <tr>
          <th><%= f.label :address, "住所" %></th>
          <td><%= f.text_field :address, class:"room-name" %></td>
      </tr>
      <tr>
          <th><%= f.label :img, "画像" %></th>
          <td><%= f.file_field :img, class:"room-name" %></td>
      </tr>
    </table>
    <%= f.hidden_field :user_id, value: @user.id %>
    <div class="btn_room_new">
      <%= f.submit "保存"%>
    </div>
    <div class="btn_room_new">
      <%= link_to "キャンセル", :back %>
    </div>
  <% end %>
</div>

app/views/rooms/own.html.erb
<div class="room_create_list">  
  <h3>登録施設一覧</h3>
  
  <table>
    <thead>
      <tr>
        <th>施設画像</th>
        <th>施設名</th>
        <th>紹介文</th>
        <th>価格</th>
        <th>作成日</th>
      </tr>
    </thead>
  
    <tbody>
      <% @rooms.each do |room| %>
        <tr>
          <td class="img-profile">
          <% if room.img.blank?  %>
              <%= image_tag  "default_img/default-room.png" %>
          <% else %>
              <%= image_tag  "#{room.img}" %>
          <% end %>
          </td>
          <td><%= link_to room.name, room_path(room.id) %></td>
          <td><%= room.introduction %></td>
          <td><%= room.price %></td>
          <td><%= room.created_at.to_s(:datetime_jp) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/rooms/show.html.erb
<%= render "shared/search" %>
<div class="room_detail">
    <div>
        <%= link_to "←戻る", :back %>
    </div>
    <div class="warapper_room_info">
        <div>
            <% if @room.img.blank?  %>
                <%= image_tag  "default_img/default-room.png", width: "300px" %>
            <% else %>
                <%= image_tag  "#{@room.img}", width: "300px" %>
            <% end %>
        </div>
        <div>
            <table class="room_data">
                <tr>
                    <th>施設名</th>
                    <td><%= @room.name %></td>
                </tr>
                <tr>
                    <th>紹介文</th>
                    <td><%= @room.introduction %></td>
                </tr>
                <tr>
                    <th>料金</th>
                    <td>¥<%= @room.price %>〜</td>
                </tr>
                <tr>
                    <th>住所</th>
                    <td><%= @room.address %></td>
                </tr>
                <tr> 
                </tr>
            </table>
            <div class="reservation">
                <%= render "shared/error", obj: @reservation %>
                <%= form_with model: @reservation, url: reservations_confirm_path, local: true, method: :get do |f| %>
                    <table>
                        <thead>
                            <tr>
                                <th><%= f.label :check_in ,"チェックイン" %></th>
                                <th><%= f.label :check_out ,"チェックアウト" %></th>
                                <th><%= f.label :person_num ,"人数" %></th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td><%= f.date_field :check_in %></td>
                                <td><%= f.date_field :check_out %></td>
                                <td><%= f.number_field :person_num %></td>
                            </tr>
                        </tbody>
                        <tfoot>
                            <tr>
                                <% if @user %>
                                    <%= f.hidden_field :user_id, value: @user.id %>
                                    <%= f.hidden_field :room_id, value: @room.id %>
                                    <td colspan="3" class="btn_reservation"><%= f.submit "予約"%></td>
                                <% else %>
                                    <td colspan="3" class="btn_reservation"><%= link_to "ログイン", new_user_session_path %></td>
                                <% end %>
                            </tr>
                        </tfoot>
                    </table>
                <% end %>
            </div>
        </div>
    </div>
</div>